# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nyko/python/pyui-generator/pyuiGenerator_app/ui/mainWindow.ui'
#
# Created: Thu Oct 11 21:54:37 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 425)
        MainWindow.setWindowTitle("pyui-generator")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutItems = QtGui.QVBoxLayout()
        self.layoutItems.setSpacing(0)
        self.layoutItems.setObjectName("layoutItems")
        self.verticalLayout_2.addLayout(self.layoutItems)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarFile = QtGui.QToolBar(MainWindow)
        self.toolBarFile.setObjectName("toolBarFile")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.toolBarItem = QtGui.QToolBar(MainWindow)
        self.toolBarItem.setObjectName("toolBarItem")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarItem)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setText("quit")
        self.actionQuit.setIconText("quit")
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setText("save")
        self.actionSave.setIconText("save")
        self.actionSave.setShortcut("Ctrl+S")
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon3)
        self.actionLoad.setText("load")
        self.actionLoad.setIconText("load")
        self.actionLoad.setShortcut("Ctrl+O")
        self.actionLoad.setObjectName("actionLoad")
        self.actionNew = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon4)
        self.actionNew.setText("new")
        self.actionNew.setIconText("new")
        self.actionNew.setShortcut("Ctrl+N")
        self.actionNew.setObjectName("actionNew")
        self.actionAddItem = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddItem.setIcon(icon5)
        self.actionAddItem.setText("addItem")
        self.actionAddItem.setIconText("addItem")
        self.actionAddItem.setShortcut("Ctrl++")
        self.actionAddItem.setObjectName("actionAddItem")
        self.actionGenerateAll = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/execAll"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerateAll.setIcon(icon6)
        self.actionGenerateAll.setText("generateAll")
        self.actionGenerateAll.setIconText("generateAll")
        self.actionGenerateAll.setShortcut("Ctrl+G")
        self.actionGenerateAll.setObjectName("actionGenerateAll")
        self.actionSync = QtGui.QAction(MainWindow)
        self.actionSync.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/autoSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSync.setIcon(icon7)
        self.actionSync.setIconText("autoGenerate")
        self.actionSync.setObjectName("actionSync")
        self.actionAddMulti = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/addMulti.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddMulti.setIcon(icon8)
        self.actionAddMulti.setText("addMulti")
        self.actionAddMulti.setIconText("addMulti")
        self.actionAddMulti.setShortcut("Ctrl+M")
        self.actionAddMulti.setObjectName("actionAddMulti")
        self.toolBarFile.addAction(self.actionQuit)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionNew)
        self.toolBarFile.addAction(self.actionLoad)
        self.toolBarFile.addAction(self.actionSave)
        self.toolBarItem.addAction(self.actionAddItem)
        self.toolBarItem.addAction(self.actionAddMulti)
        self.toolBarItem.addAction(self.actionGenerateAll)
        self.toolBarItem.addAction(self.actionSync)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.toolBarFile.setWindowTitle(QtGui.QApplication.translate("MainWindow", "project", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBarItem.setWindowTitle(QtGui.QApplication.translate("MainWindow", "file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setToolTip(QtGui.QApplication.translate("MainWindow", "Save project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setToolTip(QtGui.QApplication.translate("MainWindow", "Load project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setToolTip(QtGui.QApplication.translate("MainWindow", "New project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddItem.setToolTip(QtGui.QApplication.translate("MainWindow", "Add a file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerateAll.setToolTip(QtGui.QApplication.translate("MainWindow", "Generate all files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSync.setText(QtGui.QApplication.translate("MainWindow", "sync", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSync.setToolTip(QtGui.QApplication.translate("MainWindow", "synchronize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSync.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddMulti.setToolTip(QtGui.QApplication.translate("MainWindow", "Add several files", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
